server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://127.0.0.1:3306/chat?characterEncoding=utf8&serverTimezone=Hongkong&useSSL=false&allowPublicKeyRetrieval=true
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 500
      login-timeout: 500
      validation-timeout: 1000
      initialization-fail-timeout: 1000
      connection-test-query: select 1

#mybatis plus
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id

logging:
  config:
    - log4j2.yml